### ISSUE TITLE
Adding constant values after initialization

### ISSUE THREAD

**Issue by andrewda** [dominikWin/badlog#7]
We're trying out Badlog on our robot this year, and it's been pretty enjoyable to work with so far! One problem we've run into, though, is saving a constant value (i.e. not a graph) after the initialization is complete. An example use case of this would be logging the selected auto mode immediately before auto begins, or logging the alliance when the Driver Station connects.

One workaround we've tried is instead assigning a numeric value to each auto mode and then graphing it and matching value that back to the specific auto after the match, but this is much more complicated than it could.

I believe this would require changing the header of the file in order to update the constants. Would this be possible?

**Comment by dominikWin** [comment]
It is possible, but this was one of the accepted drawbacks with this approach. The append only approach keeps our code simple and the file system happy.

One of the things we did last year is delayed robot initialization (See BadRobot2018 repo), where we waited for robot comms (or state change for safety) before setup. This gives you access to accurate time, alliance, and event info, etc. You could, in theory, wait until you have your auto routine selected before initializing logging, but I would advise against this.

This does bring up a good point for future expansion though. The white paper mentions an expansion where you add json to each row in the CSV, but that may not be nessesary. Currently badlogvis (which I assume you’re using) only supports numeric data, but what if there was some attribute that defines an append only event log (maybe “string” or “log” or “event”), where instead of a number it took a string. Empty strings would obviously be ignored, but any value would be added to that topics “log”. You could even throw in a timestamp (from xaxis) to show when the message appeared. This could then be concatinated across the whole match and displayed as non-formatted text and embedded. This effectively adds event logging for an arbitrary number of channels, and I think this could be useful. This would involve no change to the badlog library or the file formatting. It would add a third supported type to badlogvis, but since its a stable Rust program this complexity is negligible.

For your example you would have something like this in your badlogvis:
### Some/Folder/Autonomous Selection
```
[18.3425 s] Selected cargo ship autonomous routine
```
And code would be like this:
```
BadLog.createTopicSubscriber("Some/Folder/Auto Selection Log", BadLog.UNITLESS, DataInferMode.DEFAULT, “log”);
// When the event happens
BadLog.publish(“Some/Folder/Auto Selection Log”, “Selected cargo ship autonomous routine”);
```
This could get weird because of the (-1.0) being logged as a default, but that can be replaced with an empty string as a special case for the attribute. Proabably just throw out anything that can be parsed as numeric.
The nice thing is, since it’s also time series, if you change your selection it will also show here.

A drawback would be that this only supports one line per update, but that might not nessesarly be a bad thing, since an argument could be made you should use two of these log topics.

I guess this is somewhat of an impromptu RFC now, so I might tag some others.

**Comment by andrewda** [comment]
I like that idea a lot!

> This could get weird because of the (-1.0) being logged as a default, but that can be replaced with an empty string as a special case for the attribute. Proabably just throw out anything that can be parsed as numeric.

A good way to manage this (or possibly a separate attribute) might be to only log when the value changes. That way the output might look something like this:

```
[0.0000 s] Selected auto: -1                         <-- value starts at -1 
[18.3425 s] Selected auto: rocket front              <-- driver selects a new mode
[23.5243 s] Selected auto: cargo ship front          <-- driver selects a new mode
```

I like having the `-1` there as it makes it explicitly clear that the state changes from `nothing` to `something`.

**Comment by dominikWin** [comment]
Okay, so I just put out badlogvis 0.3.0, which supports a `log` attribute. [Here](https://github.com/dominikWin/badlog/files/2898259/testfile.badbag.html.gz) is a minimal example of it working.

**Comment by andrewda** [comment]
Wow, thanks for getting that together so quickly!

One suggestion -- instead of wrapping the logs in `<code>`, which looks like this with multiple lines:

![image](https://user-images.githubusercontent.com/10191084/53305163-cff57100-3832-11e9-801f-a47f3546d20e.png)

wrapping in `<pre>` might look a little cleaner:

![image](https://user-images.githubusercontent.com/10191084/53305178-029f6980-3833-11e9-80a6-cc55a76f42ee.png)

I'm super excited to try this out a little later today. Thanks again for the insanely quick work!
